
services:
  # ──────────────────────────────
  # State store
  # ──────────────────────────────
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      retries: 15

  # ──────────────────────────────
  # FastAPI + Socket‑IO back‑end
  # ──────────────────────────────
  web:
    build: ./backend
    command: ["uvicorn", "antfarm.web:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      - redis

  # ──────────────────────────────
  # Swarm workers
  # (scale with `docker compose up --scale worker=N`)
  # ──────────────────────────────
  worker:
    build: ./backend
    command: ["python", "-m", "antfarm.worker"]
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    restart: always

  # ──────────────────────────────
  # Static Vite/React front‑end
  # ──────────────────────────────
  frontend:
    build:
      context: ./frontend      # Vite project root
    ports:
      - "3000:80"              # host 3000 → container 80 (Nginx)
    depends_on:
      - web
