name: CI

on: [push, pull_request]

jobs:
  # ──────────────────────────
  # 1) Python backend tests
  # ──────────────────────────
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip download wheel‑house
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/backend/dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          # same deps as backend/Dockerfile
          pip install \
            python-socketio[asyncio_client] \
            fastapi[all] redis asyncio uvicorn[standard] \
            pytest

      - name: Run tests
        run: pytest -q
        env:
          # point tests at a local redis‑service (declared below)
          REDIS_URL: redis://localhost:6379

    services:          # ephemeral Redis for test run
      redis:
        image: redis:7
        ports: ['6379:6379']
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 2s
          --health-retries 15

  # ──────────────────────────
  # 2) Front‑end build check
  # ──────────────────────────
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install & build
        working-directory: frontend
        run: |
          npm ci --ignore-scripts
          npm run build

  # ──────────────────────────
  # 3) Docker‑Compose build
  #    (only if the two steps above passed)
  # ──────────────────────────
  docker-build:
    runs-on: ubuntu-latest
    needs: [backend, frontend]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Build‑Kit
        uses: docker/setup-buildx-action@v3

      - name: Build all images
        run: docker compose -f docker-compose.yml build
